<div class="card o-hidden border-0 shadow-lg my-5">
    <div class="card-body p-0">
        <!-- Nested Row within Card Body -->
        <div class="row">
            <div class="col-lg-5 d-none d-lg-block bg-register-image"></div>
            <div class="col-lg-7">
                <div class="p-5">
                    <div class="text-center">
                        <h1 class="h4 text-gray-900 mb-4">Create an Account!</h1>
                    </div>
                    <?php
                    $form->setAttribute('action', $this->url('registration', array('action' => 'index')));
                    $form->prepare();
                    ?>
                    <?php echo $this->form()->openTag($form); ?>
                    <div class="form-group">
                        <?php echo $this->formHidden($form->get('id')); ?>
                    </div>
                    <div class="form-group">
                        <?php echo $this->formInput($form->get('user_name')); ?>
                        <span class="text text-danger"><?php echo $this->formElementErrors($form->get('user_name')); ?></span>
                    </div>
                    <div class="form-group">
                        <?php echo $this->formInput($form->get('email_id')); ?>
                        <span class="text text-danger"><?php echo $this->formElementErrors($form->get('email_id')); ?></span>
                    </div>
                    <div class="form-group">
                        <?php echo $this->formInput($form->get('password')); ?>
                        <span class="text text-danger"><?php echo $this->formElementErrors($form->get('password')); ?></span>
                    </div>
                    <div class="form-group">
                        <?php echo $this->formInput($form->get('confirmPassword')); ?>
                        <span class="text text-danger"><?php echo $this->formElementErrors($form->get('confirmPassword')); ?></span>
                    </div>
                    <div class="form-group">
                        <?php echo $this->formSubmit($form->get('submit')); ?>
                    </div>
                    <?php echo $this->form()->closeTag(); ?>
                    <hr>
                    <div class="text-center">
                        <a class="small" href="">Forgot Password?</a>
                    </div>
                    <div class="text-center">
                        <a class="small" href="<?php echo $this->url('auth', array('action' => 'index')) ?>">Already have an account? Login!</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>