<div class="container">

    <!-- Outer Row -->
    <div class="row justify-content-center">

        <div class="col-xl-10 col-lg-12 col-md-9">

            <div class="card o-hidden border-0 shadow-lg my-5">
                <div class="card-body p-0">
                    <!-- Nested Row within Card Body -->
                    <div class="row">
                        <div class="col-lg-6 d-none d-lg-block bg-login-image"></div>
                        <div class="col-lg-6">
                            <div class="p-5">
                                <div class="text-center">
                                    <h1 class="h4 text-gray-900 mb-4">Welcome Back!</h1>
                                </div>
                                <?php //var_dump($loginForm->getMessages()); ?>
                                <?php
                                $loginForm->setAttribute('action', $this->url('auth', array('action' => 'index')));
                                $loginForm->prepare();
                                ?>
                                <?php echo $this->form()->openTag($loginForm); ?>
                                <div class="form-group">
                                    <?php echo $this->formInput($loginForm->get('emailId')); ?>
                                    <span class="text text-danger"><?php echo $this->formElementErrors($loginForm->get('emailId')); ?></span>
                                </div>
                                <div class="form-group">
                                    <?php echo $this->formInput($loginForm->get('password')); ?>
                                    <span class="text text-danger"><?php echo $this->formElementErrors($loginForm->get('password')); ?></span>
                                </div>
                                <div class="form-group">
                                    <?php
                                    echo $this->formRow($loginForm->get('loginCsrf'));
                                    echo $this->formSubmit($loginForm->get('submit'));
                                    ?>
                                </div>
                                <?php echo $this->form()->closeTag(); ?>
                                <hr>
                                <div class="text-center">
                                    <a class="small" href="{{path('forgot.password')}}">Forgot Password?</a>
                                </div>
                                <div class="text-center">
                                    <a class="small" href="<?php echo $this->url('registration') ?>">Create an Account!</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>

    </div>

</div>