<?php

$title = 'Add new post';
$this->headTitle($title);
?>
<!-- Page Heading -->
<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">Add new Post</h1>
    <a href="<?php echo $this->url('post', array('action' => 'index')); ?>" class="btn btn-info ">
        <i class="fa fa-arrow-left"></i>
    </a>

</div>

<!-- Content Row -->
<div class="row">

    <div class="col-md-1  "></div>
    <div class="col-md-6">
        <?php
        $form->setAttribute('action', $this->url('post', array('controller' => 'post', 'action' => 'add')));
        $form->prepare();

        echo $this->form()->openTag($form);
        echo $this->formHidden($form->get('id'));
        echo $this->formRow($form->get('title'));
        echo $this->formRow($form->get('description'));
        echo $this->formSubmit($form->get('submit'));
        echo $this->form()->closeTag(); ?>

    </div>
</div>
<script>
    $(document).ready(function() {
        $('.content').richText();
    });
</script>